Load config on first access
Statically initializing this field causes a NoClassDefFoundError when
loading in Jenkins. The required classes are in libraries only visible
to the plugin's ClassLoader, not the ClassLoader used for
initialization.

See https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/